version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=D5#fLp@9kV!zQ1m$
    ports:
      - "1433:1433"
    networks:
      - fincontrol-network
    volumes:
      - sqlserver_data:/var/opt/mssql

  # Serviço para a aplicação Spring Boot
  app:
    build: .
    container_name: fincontrol_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://db:1433;databaseName=fincontrol
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=D5#fLp@9kV!zQ1m$
    networks:
      - fincontrol-network

networks:
  fincontrol-network:

volumes:
  sqlserver_data:
