INSERT INTO dominio_beneficio (nom) VALUES ('Vale Alimentação');
INSERT INTO dominio_beneficio (nom) VALUES ('Vale Refeição');
INSERT INTO dominio_beneficio (nom) VALUES ('Cartão Flash');
INSERT INTO dominio_despesa (nom) VALUES ('Essencial');
INSERT INTO dominio_despesa (nom) VALUES ('Necessidade');
INSERT INTO dominio_despesa (nom) VALUES ('Outros');
INSERT INTO dominio_pagamento (nom) VALUES ('Benefício');
INSERT INTO dominio_pagamento (nom) VALUES ('Pix');
INSERT INTO dominio_pagamento (nom) VALUES ('Cartão');
INSERT INTO dominio_pagamento (nom) VALUES ('Boleto');
INSERT INTO dominio_pagamento (nom) VALUES ('Dinheiro');
INSERT INTO item (nom) VALUES ('Internet');
INSERT INTO item (nom) VALUES ('Energia elétrica');
INSERT INTO item (nom) VALUES ('Condomínio');
INSERT INTO item (nom) VALUES ('Prestação do apartamento');
INSERT INTO item (nom) VALUES ('Supermercado');
INSERT INTO item (nom) VALUES ('Netflix');
INSERT INTO item (nom) VALUES ('Prime');
INSERT INTO item (nom) VALUES ('HBO MAX');
INSERT INTO item (nom) VALUES ('Discovery');
INSERT INTO item (nom) VALUES ('Crunchyroll');
INSERT INTO item (nom) VALUES ('Paramount');
INSERT INTO item (nom) VALUES ('Uber');
INSERT INTO item (nom) VALUES ('99Pop');
INSERT INTO item (nom) VALUES ('Ifood');