INSERT INTO dominio_beneficio (id, nom) VALUES (1, 'Vale Alimentação');
INSERT INTO dominio_beneficio (id, nom) VALUES (2, 'Vale Refeição');
INSERT INTO dominio_beneficio (id, nom) VALUES (3, 'Cartão Flash');
INSERT INTO dominio_despesa (id, nom) VALUES (1, 'Essencial');
INSERT INTO dominio_despesa (id, nom) VALUES (2, 'Necessidade');
INSERT INTO dominio_despesa (id, nom) VALUES (3, 'Outros');
INSERT INTO item (nom) VALUES ('Internet');
INSERT INTO item (nom) VALUES ('Energia elétrica');
INSERT INTO item (nom) VALUES ('Condomínio');
INSERT INTO item (nom) VALUES ('Prestação do apartamento');
INSERT INTO item (nom) VALUES ('Supermercado');
INSERT INTO item (nom) VALUES ('Netflix');
INSERT INTO item (nom) VALUES ('Prime');
INSERT INTO item (nom) VALUES ('HBO MAX');
INSERT INTO item (nom) VALUES ('Discovery');
INSERT INTO item (nom) VALUES ('Crunchyroll');
INSERT INTO item (nom) VALUES ('Paramount');
INSERT INTO item (nom) VALUES ('Uber');
INSERT INTO item (nom) VALUES ('99Pop');
INSERT INTO item (nom) VALUES ('Ifood');
INSERT INTO dominio_pagamento (id, nom) VALUES (1, 'Benefício');
INSERT INTO dominio_pagamento (id, nom) VALUES (2, 'Pix');
INSERT INTO dominio_pagamento (id, nom) VALUES (3, 'Cartão');
INSERT INTO dominio_pagamento (id, nom) VALUES (4, 'Boleto');
INSERT INTO dominio_pagamento (id, nom) VALUES (5, 'Dinheiro');
